name: Terraform (LocalStack) - lint & plan

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/terraform/**'

jobs:
  tflint-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start LocalStack
        run: |
          docker run -d --name localstack -p 4566:4566 --env SERVICES=s3,ecr localstack/localstack
          sleep 6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform init
        working-directory: infra/terraform
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: us-east-1
          AWS_ENDPOINT_URL: http://localhost:4566
        run: terraform init -input=false

      - name: TFLint
        run: |
          curl -sSL https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          ./tflint

      - name: Terraform validate
        working-directory: infra/terraform
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: us-east-1
        run: terraform validate
